[masters]
k8s-master-01 ansible_host=10.101.0.100
k8s-master-02 ansible_host=10.101.0.101
k8s-master-03 ansible_host=10.101.0.102

[workers]
k8s-worker-01 ansible_host=10.101.0.103
k8s-worker-02 ansible_host=10.101.0.104
k8s-worker-02 ansible_host=10.101.0.105

[k8s:children]
masters
workers

[all:vars]
#ansible_user=root
#ansible_ssh_common_args='-o StrictHostKeyChecking=no'