[masters]
k8s-master-01 ansible_host=10.69.0.10
k8s-master-02 ansible_host=10.69.0.11
k8s-master-03 ansible_host=10.69.0.12

[workers]
k8s-worker-01 ansible_host=10.69.0.20
k8s-worker-02 ansible_host=10.69.0.21
k8s-worker-03 ansible_host=10.69.0.22
k8s-worker-04 ansible_host=10.69.0.23
k8s-worker-05 ansible_host=10.69.0.24
k8s-worker-06 ansible_host=10.69.0.25
k8s-worker-07 ansible_host=10.69.0.26
k8s-worker-08 ansible_host=10.69.0.27
k8s-worker-09 ansible_host=10.69.0.28
k8s-worker-10 ansible_host=10.69.0.29
k8s-worker-11 ansible_host=10.69.0.30
k8s-worker-12 ansible_host=10.69.0.31
k8s-worker-13 ansible_host=10.69.0.32
k8s-worker-14 ansible_host=10.69.0.33
k8s-worker-15 ansible_host=10.69.0.34
k8s-worker-16 ansible_host=10.69.0.35
k8s-worker-17 ansible_host=10.69.0.36
k8s-worker-18 ansible_host=10.69.0.37
k8s-worker-19 ansible_host=10.69.0.38
k8s-worker-20 ansible_host=10.69.0.39
k8s-worker-21 ansible_host=10.69.0.40

[k8s:children]
masters
workers

[all:vars]
#ansible_user=root
#ansible_ssh_common_args='-o StrictHostKeyChecking=no'