apiVersion: v1
kind: Namespace
metadata:
  name: {{ democratic_csi_namespace }}
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: v1
kind: Secret
metadata:
  name: truenas-iscsi-driver-config
  namespace: {{ democratic_csi_namespace }}
type: Opaque
stringData:
  driver-config-file.yaml: |
    driver: freenas-api-iscsi
    instance_id:
    httpConnection:
      protocol: https
      host: {{ democratic_csi_truenas_host }}
      port: 443
      apiKey: "{{ democratic_csi_truenas_api_key }}"
      allowInsecure: true
    zfs:
      datasetProperties:
{% raw %}
        "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
{% endraw %}
      datasetParentName: {{ democratic_csi_dataset_vols }}
      detachedSnapshotsDatasetParentName: {{ democratic_csi_dataset_snaps }}
      zvolCompression:
      zvolDedup:
      zvolEnableReservation: false
      zvolBlocksize: {{ democratic_csi_zvol_blocksize }}
    iscsi:
      targetPortal: "{{ iscsi_portal_host }}:{{ iscsi_portal_port }}"
      targetPortals: []
      interface:
      namePrefix: csi-
      nameSuffix: "-k8s"
      targetGroups:
        - targetGroupPortalGroup: {{ democratic_csi_portal_group }}
          targetGroupInitiatorGroup: {{ democratic_csi_initiator_group }}
          targetGroupAuthType: None
          targetGroupAuthGroup:
{% raw %}
      extentCommentTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
{% endraw %}
      extentInsecureTpc: true
      extentXenCompat: false
      extentDisablePhysicalBlocksize: false
      extentBlocksize: 4096
      extentRpm: "SSD"
      extentAvailThreshold: 0
