---
- name: Copy etcd archive to master
  ansible.builtin.copy:
    src: "{{ src_pkg_dir }}/etcd-v{{ etcdctl_version }}-linux-amd64.tar.gz"
    dest: /tmp/etcd-v{{ etcdctl_version }}-linux-amd64.tar.gz
    mode: '0644'

- name: Extract etcdctl binary
  ansible.builtin.unarchive:
    src: /tmp/etcd-v{{ etcdctl_version }}-linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: Install etcdctl
  ansible.builtin.copy:
    src: /tmp/etcd-v{{ etcdctl_version }}-linux-amd64/etcdctl
    dest: /usr/local/bin/etcdctl
    mode: '0755'
    remote_src: yes

- name: Cleanup temp files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/etcd-v{{ etcdctl_version }}-linux-amd64.tar.gz
    - /tmp/etcd-v{{ etcdctl_version }}-linux-amd64